{
 "title": "librdkafka - librdkafka Consumers / Producers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "client_id", "label": "Client Id", "query": "label_values(client_id)" },
   { "name": "broker_id", "label": "Broker Id", "query": "label_values(broker_id)" },
   { "name": "topic", "label": "Topic", "query": "label_values(topic)" },
   { "name": "partition_id", "label": "Partition Id", "query": "label_values(partition_id)" },
   {
    "name": "app_name",
    "label": "Application Name",
    "query": "label_values(app_kubernetes_io_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Common",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of ops  waiting in queue",
     "type": "graph",
     "description": "Number of ops (callbacks, events, etc) waiting in queue for application to serve with rd_librdkafka_poll()",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "librdkafka_replyq", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Number of connection attempts per broker",
     "type": "graph",
     "description": "Number of connection attempts, including successful and failed, and name resolution failures.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "librdkafka_connects", "legendFormat": "{{name}} - {{broker}}" }
     ]
    },
    {
     "title": "Broker latency / round-trip time in microseconds ",
     "type": "graph",
     "description": "Broker latency / round-trip time in microseconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "librdkafka_brokers_rtt_avg", "legendFormat": "{{name}} - {{broker}}" }
     ]
    },
    {
     "title": "Number of disconnects  per broker",
     "type": "graph",
     "description": "Number of disconnects (triggered by broker, network, load-balancer, etc.).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "librdkafka_broker_disconnects", "legendFormat": "{{name}} - {{broker}}" }
     ]
    },
    {
     "title": "Total number of errors per broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "librdkafka_broker_error_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
       "legendFormat": "{{name}} - {{broker}}"
      }
     ]
    },
    {
     "title": "Batch sizes in bytes average per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "librdkafka_topics_batchsize_avg",
       "legendFormat": "{{name}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Batch message counts average per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "librdkafka_topics_batchcnt_avg", "legendFormat": "{{name}} - {{topic}}" }
     ]
    }
   ]
  },
  {
   "title": "librdkafka Producers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total number of messages produced (librdkafka_txmsgs)",
   "type": "gauge",
   "description": "librdkafka_txmsgs",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librdkafka_txmsgs{type=\"producer\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total number of request produced",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librdkafka_tx{type=\"producer\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of messages awaiting transmission to broker ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "librdkafka_outbuf_msg_cnt{type=\"producer\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Current total size of messages in producer queues",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "librdkafka_msg_size{type=\"producer\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Maximum total size of messages allowed on the producer queues",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "librdkafka_msg_size_max{type=\"producer\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current total size of messages in producer queues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "librdkafka_msg_size{type=\"producer\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current number of messages in producer queues",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "librdkafka_msg_cnt{type=\"producer\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ratio number of bytes transmitted to librdkafka brokers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(librdkafka_tx_bytes{type=\"producer\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of messages in-flight to broker awaitign response per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_message_in_flight_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Ratio number of message bytes transmitted to librdkafka brokers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(librdkafka_transmitted_message_bytes_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total number of request retries per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_retries_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Number of requests awaiting transmission to broker per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_request_awaiting_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Number of disconnects  per broker",
   "type": "graph",
   "description": "Number of disconnects (triggered by broker, network, load-balancer, etc.).",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_disconnection_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Number of requests in-flight to broker awaiting response per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_request_in_flight_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Internal request queue latency per broker",
   "type": "graph",
   "description": "Internal request queue latency in microseconds. This is the time between a request is enqueued on the transmit (outbuf) queue and the time the request is written to the TCP socket. Additional buffering and latency may be incurred by the TCP stack and network",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_internal_request_queue_latency_ms{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Total number of requests timed out per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_timeout_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Total number of bytes transmitted per partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "librdkafka_partition_transmitted_message_bytes_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", topic=~\"$topic\", partition_id=~\"$partition_id\"}",
     "legendFormat": "{{name}} - {{topic}} -{{partition_id}}"
    }
   ]
  },
  {
   "title": "Number of connection attempts per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_connection_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Internal producer queue latency per broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "librdkafka_broker_internal_queue_latency_ms{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", broker_id=~\"$broker_id\"}",
     "legendFormat": "{{name}} - {{broker}}"
    }
   ]
  },
  {
   "title": "Total number of messages transmitted per partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "librdkafka_partition_transmitted_message_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", topic=~\"$topic\", partition_id=~\"$partition_id\"}",
     "legendFormat": "{{name}} - {{topic}} -{{partition_id}}"
    }
   ]
  },
  {
   "title": "Current number of messages in-flight to/from broker per partition",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "librdkafka_partition_message_in_flight_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\", topic=~\"$topic\", partition_id=~\"$partition_id\"}",
     "legendFormat": "{{name}} - {{topic}} -{{partition_id}}"
    }
   ]
  },
  {
   "title": "librdkafka Consumers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total number of messages consumed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "librdkafka_consumed_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Consumer lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "librdkafka_partition_lag{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", partition_id=~\"$partition_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}}- {{topic}} - {{broker}} - {{partition_id}}"
      }
     ]
    },
    {
     "title": "Total number of responses received per broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "librdkafka_broker_responses_total{app_kubernetes_io_name=~\"$app_name\", broker_id=~\"$broker_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}} - {{broker}}"
      }
     ]
    },
    {
     "title": "Ratio number of message bytes received from librdkafka brokers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(librdkafka_bytes_consumed_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total number of bytes received per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "librdkafka_broker_responses_byte_total{app_kubernetes_io_name=~\"$app_name\", broker_id=~\"$broker_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}} - {{broker}}"
      }
     ]
    },
    {
     "title": "Ratio number of bytes received from librdkafka brokers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(librdkafka_bytes_received_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total number of bytes received per partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "librdkafka_partition_message_bytes_consumed_total{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", partition_id=~\"$partition_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}} - {{topic}} - {{broker}} - {{partition_id}}"
      }
     ]
    },
    {
     "title": "Total number of responses received from librdkafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "librdkafka_responses_received_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total number of messages consumed per partition",
     "type": "graph",
     "description": "Total number of messages consumed, not including ignored messages per partition",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "librdkafka_partition_message_consumed_total{app_kubernetes_io_name=~\"$app_name\", topic=~\"$topic\", partition_id=~\"$partition_id\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}} - {{topic}} - {{broker}} - {{partition_id}}"
      }
     ]
    },
    {
     "title": "Time elapsed since last rebalance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "librdkafka_rebalance_age{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total number of rebalances",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "librdkafka_rebalance_total{app_kubernetes_io_name=~\"$app_name\", client_id=~\"$client_id\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}